"""E2E crypto parity tests.

Ports the upstream behavioral tests (CRYPTO-1..6 from
packages/e2e-crypto/e2e-crypto.test.ts) and adds hardcoded cross-implementation
vectors generated by running the ACTUAL TypeScript implementation
(`npx tsx gen_vectors.ts` against packages/e2e-crypto/e2e-crypto.ts) with the
same password/userId — so a drift in KDF params, nonce derivation, or the
cipher shows up as a hard failure, not just a self-consistent round-trip.
"""

import pytest

from botschat.e2e import (  # noqa: E402
    decrypt_bytes,
    decrypt_text,
    derive_key,
    encrypt_bytes,
    encrypt_text,
    from_base64,
    to_base64,
)

PASSWORD = "test-password"
USER_ID = "u_test_user_123"

# Generated from the real TS implementation (e2e-crypto.ts) on 2026-08-30.
TS_KEY_B64 = "zJ1blqFpYH5hoHUtrXjw8Fq9jYTOo+G4H0STrhx8KZM="
TS_VECTORS = {
    # (plaintext, contextId) -> base64 ciphertext
    ("Hello 世界 🔐", "msg-abc-123"): "LSAvahNx/FOjAnXfz8InucI=",
    ("short", "ctx-1"): "Z3uIBFw=",
    ("same", "ctx-deterministic"): "oi300g==",
    ("ab", "msg-2bytes"): "9zQ=",
    ("The quick brown fox jumps over the lazy dog", "vector-5"):
        "cjOFtgPgy9b4zHYCqPsCZ3cv6FN8Owba7LKprcAuNXJ+hs6ia4Vhn01Dvg==",
    ("", "empty-msg"): "",
}
TS_BYTES_VECTOR = {
    # (raw bytes, contextId) -> base64 ciphertext
    (bytes([0x00, 0x01, 0xFF, 0xFE, 0x42]), "bytes-1"): "XwzNL6g=",
}


@pytest.fixture(scope="module")
def key():
    return derive_key(PASSWORD, USER_ID)


def test_crypto1_key_derivation_consistent():
    """CRYPTO-1: same password+userId yields the same 32-byte key."""
    k1 = derive_key(PASSWORD, USER_ID)
    k2 = derive_key(PASSWORD, USER_ID)
    assert len(k1) == 32
    assert k1 == k2


def test_crypto1b_key_matches_ts_implementation():
    """The derived key must byte-match the TypeScript implementation."""
    assert to_base64(derive_key(PASSWORD, USER_ID)) == TS_KEY_B64


def test_crypto2_roundtrip(key):
    """CRYPTO-2: decrypt(encrypt(plaintext)) === plaintext."""
    plaintext = "Hello 世界 🔐"
    ct = encrypt_text(key, plaintext, "msg-abc-123")
    assert decrypt_text(key, ct, "msg-abc-123") == plaintext


def test_crypto3_zero_expansion_no_prefix(key):
    """CRYPTO-3: ciphertext length == UTF-8 plaintext length; no prefix."""
    plaintext = "short"
    ct = encrypt_text(key, plaintext, "ctx-1")
    assert len(ct) == len(plaintext.encode("utf-8"))
    assert ct != b""
    assert not to_base64(ct).startswith("e2e:")


def test_crypto4_wrong_key_or_context_fails(key):
    """CRYPTO-4: wrong key/contextId must NOT reveal the plaintext."""
    plaintext = "secret"
    ct = encrypt_text(key, plaintext, "msg-1")
    wrong_key = derive_key("wrong-password", USER_ID)
    assert decrypt_text(wrong_key, ct, "msg-1") != plaintext
    assert decrypt_text(key, ct, "wrong-context-id") != plaintext


def test_crypto5_deterministic_same_context(key):
    """CRYPTO-5: same plaintext+contextId yields identical ciphertext."""
    ct1 = encrypt_text(key, "same", "ctx-deterministic")
    ct2 = encrypt_text(key, "same", "ctx-deterministic")
    assert ct1 == ct2


def test_crypto6_short_plaintext_zero_expansion(key):
    """CRYPTO-6: 2-byte plaintext -> 2-byte ciphertext."""
    ct = encrypt_text(key, "ab", "msg-2bytes")
    assert len(ct) == 2
    assert decrypt_text(key, ct, "msg-2bytes") == "ab"


def test_bytes_roundtrip(key):
    raw = bytes([0x00, 0x01, 0xFF, 0xFE])
    ct = encrypt_bytes(key, raw, "bytes-1")
    assert len(ct) == len(raw)
    assert decrypt_bytes(key, ct, "bytes-1") == raw


def test_ts_vectors_text(key):
    """Cross-implementation: Python ciphertext must equal TS ciphertext."""
    for (plaintext, context_id), expected_b64 in TS_VECTORS.items():
        ct = encrypt_text(key, plaintext, context_id)
        assert to_base64(ct) == expected_b64, f"contextId={context_id!r}"


def test_ts_vectors_bytes(key):
    for (raw, context_id), expected_b64 in TS_BYTES_VECTOR.items():
        ct = encrypt_bytes(key, raw, context_id)
        assert to_base64(ct) == expected_b64, f"contextId={context_id!r}"


def test_ts_decrypt_vectors(key):
    """Cross-implementation: Python decrypt must read TS ciphertext."""
    for (plaintext, context_id), expected_b64 in TS_VECTORS.items():
        ct = from_base64(expected_b64)
        assert decrypt_text(key, ct, context_id) == plaintext


def test_base64_roundtrip():
    assert from_base64(to_base64(b"\x00\xffhello")) == b"\x00\xffhello"
